version: '3'
services:
  webapp:
    build:
      context: ./
    image: envirocar/webapp:latest
    environment:
      - EC_BASE_URL=https://envirocar.org/auth-proxy/api
      - EC_BASE=https://envirocar.org/auth-proxy
      - EC_WEBSITE_BASE=https://envirocar.org/
      - EC_SERVER_BASE=https://envirocar.org/api/stable
    ports:
      - 8080:80
    expose:
      - 80
